import { Eye, FileText, Headphones, NotePencil, PlayCircle, UsersThree } from "@phosphor-icons/react";
import type { ResearchSession } from "../../lib/researchSessions";
import { getPmSessionTranscript } from "../../mock/pmSessionTranscripts";
import { EvidenceCards, SessionSummary } from "./SessionDetail";

export default function PmSessionDetail({ session }: { session: ResearchSession }) {
  const transcript = getPmSessionTranscript(session.id);
  return <><SessionSummary session={session} /><section className="session-pm-grid" aria-label="PM session operations"><article className="session-pm-note"><NotePencil size={22} weight="duotone" /><p className="research-eyebrow">Research note</p><h2>PM interpretation</h2><p>{session.pmNote}</p></article><article className="session-recording"><Headphones size={22} weight="duotone" /><p className="research-eyebrow">Recording</p><h2>Recording placeholder</h2><p>Playback becomes available when the interview recording is attached.</p><button type="button"><PlayCircle size={18} weight="fill" /> Preview recording</button></article><article className="session-observer-controls"><UsersThree size={22} weight="duotone" /><p className="research-eyebrow">Observer room</p><h2>Observer controls</h2><div><button type="button"><Eye size={17} /> Open observer view</button><button type="button">Share session brief</button></div></article></section><EvidenceCards session={session} /><section className="session-transcript" aria-labelledby="session-transcript-title"><div className="session-section-heading"><FileText size={21} weight="duotone" /><div><p className="research-eyebrow">Full research record</p><h2 id="session-transcript-title">Transcript</h2></div></div>{transcript ? <div className="session-transcript__turns">{transcript.map((turn) => <article className={`session-transcript__turn session-transcript__turn--${turn.speaker}`} key={turn.id}><span>{turn.timestamp}</span><div><strong>{turn.speakerName}</strong><p>{turn.translatedText}</p></div></article>)}</div> : <p className="session-transcript__empty">No transcript is attached to this session yet.</p>}</section></>;
}
